import metamaskConfig from '@metamask/eslint-config';
import metamaskNodeConfig from '@metamask/eslint-config-nodejs';
import metamaskTypescriptConfig from '@metamask/eslint-config-typescript';
import metamaskJestConfig from '@metamask/eslint-config-jest';

export default [
  {
    ignores: [
      '**/dist*/',
      '**/scripts/**/*.js',
      'jest.config.base.js',
      'jest.config.js',
      'packages/snap/jest.config.js',
      'packages/connector/jest.config.js',
      '**/*__GENERATED__*',
      '**/build',
      '**/public',
      '**/.cache',
      '.prettierrc.js',
      '.yarn/**',
      'eslint.config.mjs',
      '**/eslint.config.mjs',
      'packages/connector/.eslintrc.js',
      'packages/connector/postbuild.js',
      'packages/connector/src/tests/**',
      'packages/snap/build.js',
      'packages/snap/post-process.js',
      'packages/snap/snap.config.ts',
      'packages/snap/src/tests/**',
    ],
  },
  ...metamaskConfig,
  ...metamaskNodeConfig,
  ...metamaskTypescriptConfig,
  {
    files: ['**/*.{ts,tsx}'],
    rules: {
      '@typescript-eslint/no-shadow': ['error', { allow: ['Text'] }],
      '@typescript-eslint/consistent-type-definitions': ['error', 'type'],
      '@typescript-eslint/no-non-null-assertion': 0,
      'no-restricted-globals': 0,
      '@typescript-eslint/naming-convention': 0,
      '@typescript-eslint/prefer-nullish-coalescing': 0,
      'id-length': 0,
      'id-denylist': 0,
      '@typescript-eslint/restrict-template-expressions': 0,
      '@typescript-eslint/unbound-method': 0,
      '@typescript-eslint/no-unnecessary-type-assertion': 0,
      '@typescript-eslint/restrict-plus-operands': 0,
      '@typescript-eslint/explicit-function-return-type': 0,
      '@typescript-eslint/no-misused-promises': 0,
      '@typescript-eslint/consistent-type-exports': 0,
      'n/no-unsupported-features/node-builtins': 0,
      'n/callback-return': 0,
      '@typescript-eslint/no-base-to-string': 0,
      '@typescript-eslint/ban-ts-comment': 0,
      '@typescript-eslint/no-implied-eval': 0,
      '@typescript-eslint/no-require-imports': 0,
      'import-x/no-unassigned-import': 0,
      'import-x/unambiguous': 0,
      'import-x/no-extraneous-dependencies': 0,
      'jsdoc/require-jsdoc': 0,
      camelcase: 0,
      'no-nested-ternary': 0,
      'no-console': 0,
      'n/no-sync': 0,
      'no-param-reassign': 0,
      'require-atomic-updates': 0,
    },
  },
  ...metamaskJestConfig,
  {
    files: ['**/*.test.ts', '**/*.test.js'],
    rules: {
      '@typescript-eslint/no-shadow': [
        'error',
        { allow: ['describe', 'expect', 'it'] },
      ],
    },
  },
];
